spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://efub-tweeter.cbosoki4qqbu.ap-northeast-2.rds.amazonaws.com:3306/efubtweeter?createDatabaseIfNotExist=true&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: admin
    password: mdmstj2395!
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  security:
    enabled: false

server:
  port: 8080
  address: 0.0.0.0
